### ISSUE TITLE
[Question] Benchmark against CDO climate indices

### ISSUE THREAD

**Issue by abel-bzz** [Ouranosinc/xclim-benchmark#6]
Did you ever run a benchmark of xclim against CDO climate indices https://code.mpimet.mpg.de/projects/cdo/embedded/cdo_eca.pdf ?

If so, would it be possible to share what you tried ? I would like to evaluate xclim/icclim perfs and make sure dask allows us to be competitive in that regard.

**Comment by huard** [comment]
I don't think we ever did.

**Comment by abel-bzz** [comment]
Ok I will try to make something and will post the results here.

**Comment by abel-bzz** [comment]
Closing this as I could not make CDO run in parallel and sequentially it is (obviously) much slower than xclim can do with dask.
